# Base configs
baseurl: "https://photography-1-tan.vercel.app/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Fotózás | Kelemen Ákos"
subtitle: "Tekintsd meg a képeimet!"
author: "Kelemen Ákos"
header:
 title: "Fotózás"
 subtitle: "Kelemen Ákos"
footer:
 name: "Üdvözöllek"
 bio: "Amatőr szintű fotós vagyok"
 github: "Ha szeretnél velem együtt dolgozni keress bizalommal"
web_design: "Kelemen Ákos"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/akoskele27"
  github: "https://www.github.com/Akos31"
